#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01

service_triggers(){
    procd_add_reload_interface_trigger "interface.*.up" wan
}

generate_config() {
    echo "" >> /etc/config/ipinfo
    echo "config ipinfo 'config'" >> /etc/config/ipinfo
    curl -s http://ip-api.com/json/\?fields=country,city,isp,query >> /etc/config/ipinfo
    sed -i 's/{"//g;                                    # Remove symbol "
            s/}//g;                                     # Remove symbol /
            s/"://g;                                    # Remove symbol ":
            s/,"/\n/g;                                  # Replace symbol ," by creating a new line
            s/country/        option country /g;        # Replace country with option country
            s/city/        option city /g;              # Replace city with option city
            s/isp/        option isp /g;                # Replace isp with option isp
            s/query/        option ip /g                # Replace query with option ip
            ' /etc/config/ipinfo
    sed -i "y/\"/'/" /etc/config/ipinfo                 # Replace all symbol " with ' 
    echo "" >> /etc/config/ipinfo
    echo "" >> /etc/config/ipinfo
}

clean(){
    rm -f /etc/config/ipinfo
}

start_service(){
    clean && generate_config
}

stop_service(){
    clean
}